{% set name = "ewah-bool-utils" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ewah_bool_utils-{{ version }}.tar.gz
  sha256: 5768183dc723149bc8e9d6181d93bf69825f643034622cc275d919afb5f84668
  patches:
    - patches/crossc-openmp.patch  # [linux]

build:
  number: 2
  python_version_independent: true  # [py>=311 and is_abi3]
  skip: true  # [py>=312 and is_abi3]
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - EWAH_BOOL_UTILS_LIMITED_API=1

requirements:
  build:
    - python-abi3                            # [py>=311 and is_abi3]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - libgomp                                # [linux]
    - setuptools
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython
    - numpy
    - pip
    - setuptools
  run:
    - python

test:
  requires:
    - pip
    - abi3audit  # [py>=311 and is_abi3]
  imports:
    - ewah_bool_utils
  commands:
    - pip check
    - abi3audit $SP_DIR/ewah_bool_utils/*.abi3.so -s -v --assume-minimum-abi3 3.11  # [unix and py>=311 and is_abi3]
    # only check a single file on windows because I can't figure out the correct wildcaard expression
    # this should be okay as long as there's nothing platform specific in `setupext.py`
    - abi3audit %SP_DIR%/ewah_bool_utils/ewah_bool_wrap.pyd -s -v --assume-minimum-abi3 3.11     # [win and py>=311 and is_abi3]

about:
  home: https://pypi.org/project/ewah-bool-utils/
  summary: EWAH Bool Array utils for yt
  license: Apache-2.0 AND BSD-3-Clause
  license_file:
    - LICENSE
    - ewah_bool_utils/cpp/LICENSE

extra:
  recipe-maintainers:
    - neutrinoceros
    - matthewturk
